// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG1_6xEADpE5eyZFcO3uNxDmYnPTOfnC4',
    appId: '1:927552561458:web:a597e3652ac6acd86ab72b',
    messagingSenderId: '927552561458',
    projectId: 'rozgarapp-76bc8',
    authDomain: 'rozgarapp-76bc8.firebaseapp.com',
    databaseURL: 'https://rozgarapp-76bc8-default-rtdb.firebaseio.com',
    storageBucket: 'rozgarapp-76bc8.firebasestorage.app',
    measurementId: 'G-XPTFXRWB15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzVf_hC-BEtMJeqNO13jrT084kkWdWcsw',
    appId: '1:927552561458:android:523d7849874125326ab72b',
    messagingSenderId: '927552561458',
    projectId: 'rozgarapp-76bc8',
    databaseURL: 'https://rozgarapp-76bc8-default-rtdb.firebaseio.com',
    storageBucket: 'rozgarapp-76bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFgG4FwqFF4nQ6FknWAjNQ-NWC5uVCVAU',
    appId: '1:927552561458:ios:2b342853935729056ab72b',
    messagingSenderId: '927552561458',
    projectId: 'rozgarapp-76bc8',
    databaseURL: 'https://rozgarapp-76bc8-default-rtdb.firebaseio.com',
    storageBucket: 'rozgarapp-76bc8.firebasestorage.app',
    iosBundleId: 'com.example.rozgaarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFgG4FwqFF4nQ6FknWAjNQ-NWC5uVCVAU',
    appId: '1:927552561458:ios:2b342853935729056ab72b',
    messagingSenderId: '927552561458',
    projectId: 'rozgarapp-76bc8',
    databaseURL: 'https://rozgarapp-76bc8-default-rtdb.firebaseio.com',
    storageBucket: 'rozgarapp-76bc8.firebasestorage.app',
    iosBundleId: 'com.example.rozgaarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG1_6xEADpE5eyZFcO3uNxDmYnPTOfnC4',
    appId: '1:927552561458:web:d211c2499360fafd6ab72b',
    messagingSenderId: '927552561458',
    projectId: 'rozgarapp-76bc8',
    authDomain: 'rozgarapp-76bc8.firebaseapp.com',
    databaseURL: 'https://rozgarapp-76bc8-default-rtdb.firebaseio.com',
    storageBucket: 'rozgarapp-76bc8.firebasestorage.app',
    measurementId: 'G-3YMZ618KPZ',
  );
}
